### ISSUE TITLE
Error when trying to load character.webp file

### ISSUE THREAD

**Issue by Chris2918** [AICatgirls/aichatgirls#12]
Traceback (most recent call last):
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\lccji\Downloads\aichatgirls\aichatgirls.py", line 42, in on_ready
    character = loadCharacterCard.load_character_card(client.user.name)
  File "C:\Users\lccji\Downloads\aichatgirls\loadCharacterCard.py", line 27, in load_character_card
    metadata = json.loads(json_string)
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Also, perhaps implement support for .png files?

**Comment by AICatgirls** [comment]
Thank you for reporting. The real problem I'm facing at the moment is that the text-generation-webui API requires a character to be selected from its own character folder, otherwise it defaults to the Assistant character which doesn't make for a good chatbot. It doesn't necessarily stop me from fixing this issue or adding .png support, but with that block downstream the character won't be able to come alive.

So I'm researching how to convert this app to be an extension of text-generation-webui, which ideally would let me bypass the API and get us back to roleplaying.

If you could send me the character card then I'll be able to reproduce the problem and make a fix for loading it. It's just going to be a minute before we'll be able to really play with them.

**Comment by Chris2918** [comment]
[character.zip](https://github.com/AICatgirls/aichatgirls/files/13942362/character.zip)

Here is my character.webp file in a .zip archive.

**Comment by AICatgirls** [comment]
@Chris2918 I have this working for the card you provided, and I fixed the API issue. Would you please give it a try and let me know if it works or not?

I need to figure out a user interface for switching between character cards, after which I'll add .png support; I'm still working on it

**Comment by Chris2918** [comment]
It works!

**Comment by Chris2918** [comment]
Thank you
